# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_model', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('entry', 'Entry'), ('enhanced', 'Enhanced'), ('internet_of_things', 'Internet Of Things'), ('wearable', 'Wearable'), ('3D_printing', '3D Printing')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.CharField(max_length=50000)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduino.Card')),
            ],
        ),
    ]
